-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE RETAIL_SOCIAL_COMMERCE;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.STORES (
  STORE_ID VARCHAR(20) NOT NULL, STORE_NAME VARCHAR(200), CITY VARCHAR(50), REGION VARCHAR(50), FORMAT VARCHAR(30), SIZE_SQM FLOAT, OPENED_DATE DATE, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ORDERS (
  ORDER_ID VARCHAR(30) NOT NULL, STORE_ID VARCHAR(20), CUSTOMER_ID VARCHAR(20), ORDER_DATE TIMESTAMP, TOTAL_AMOUNT FLOAT, ITEMS INT, PAYMENT_METHOD VARCHAR(30), DELIVERY_TYPE VARCHAR(20), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR(20) NOT NULL, CUSTOMER_NAME VARCHAR(200), SEGMENT VARCHAR(30), REGION VARCHAR(50), REGISTRATION_DATE DATE, TOTAL_ACCOUNTS INT, LIFETIME_VALUE FLOAT, RISK_SCORE FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTS (
  PRODUCT_ID VARCHAR(20) NOT NULL, PRODUCT_NAME VARCHAR(200), CATEGORY VARCHAR(50), TENOR_MONTHS INT, PROFIT_RATE FLOAT, MIN_AMOUNT FLOAT, STATUS VARCHAR(20), LAUNCH_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
