-- Generated from generator/demo_specs/aws-philippines-retail-social-commerce.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-retail-social-commerce
-- This is the schema that is actually deployed for PH_RETAIL_SOCIAL_COMMERCE.

-- Alerts fire on the bottom tail of Social Conversion
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SOCIAL_CONVERSION) AS T
  FROM RAW.AUDIENCE_SEGMENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SOCIAL_CONVERSION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SOCIAL_CONVERSION), 2) AS AVG_SOCIAL_CONVERSION,
  ROUND(AVG(f.KPI_AVG_VIEWERS_STREAM), 2) AS AVG_VIEWERS_STREAM,
  ROUND(AVG(f.KPI_STREAM_CONVERSION), 2) AS AVG_STREAM_CONVERSION
FROM RAW.AUDIENCE_SEGMENTS f
JOIN RAW.INFLUENCERS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SOCIAL_CONVERSION), 2) AS AVG_SOCIAL_CONVERSION,
  ROUND(AVG(f.KPI_AVG_VIEWERS_STREAM), 2) AS AVG_VIEWERS_STREAM,
  ROUND(AVG(f.KPI_STREAM_CONVERSION), 2) AS AVG_STREAM_CONVERSION
FROM RAW.AUDIENCE_SEGMENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SOCIAL_CONVERSION) AS KPI_SOCIAL_CONVERSION, AVG(KPI_AVG_VIEWERS_STREAM) AS KPI_AVG_VIEWERS_STREAM, AVG(KPI_STREAM_CONVERSION) AS KPI_STREAM_CONVERSION FROM RAW.AUDIENCE_SEGMENTS),
     en AS (SELECT SUM(KPI_SOCIAL_GMV) AS KPI_SOCIAL_GMV, SUM(KPI_LIVE_STREAMS_MTD) AS KPI_LIVE_STREAMS_MTD, SUM(KPI_INFLUENCER_PARTNERS) AS KPI_INFLUENCER_PARTNERS, SUM(KPI_REPLAY_REVENUE) AS KPI_REPLAY_REVENUE FROM RAW.INFLUENCERS)
  SELECT 1 AS SORT_ORDER, 'Social GMV' AS TITLE, KPI_SOCIAL_GMV AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_SOCIAL_GMV) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Live Streams (MTD)' AS TITLE, KPI_LIVE_STREAMS_MTD AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_LIVE_STREAMS_MTD)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Influencer Partners' AS TITLE, KPI_INFLUENCER_PARTNERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INFLUENCER_PARTNERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Social Conversion' AS TITLE, KPI_SOCIAL_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOCIAL_CONVERSION), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Viewers/Stream' AS TITLE, KPI_AVG_VIEWERS_STREAM AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_AVG_VIEWERS_STREAM) / 1000), 1) AS DECIMAL(38,1))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Stream Conversion' AS TITLE, KPI_STREAM_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_STREAM_CONVERSION), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Replay Revenue' AS TITLE, KPI_REPLAY_REVENUE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_REPLAY_REVENUE) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
