-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Social Commerce Analytics & Influencer Intelligence
-- ============================================================================
USE DATABASE SOCIAL_COMMERCE;
USE SCHEMA ML;

-- ML.CLASSIFICATION: CONVERSION_PREDICTOR
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.CONVERSION_PREDICTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CONTENT_PERFORMANCE'),
  TARGET_COLNAME => 'WILL_CONVERT'
);

-- ML.FORECAST: SOCIAL_DEMAND_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.SOCIAL_DEMAND_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TRENDING_PRODUCTS'),
  SERIES_COLNAME => 'PRODUCT_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'DAILY_MENTIONS'
  
);

CREATE OR REPLACE TABLE ML.SOCIAL_DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.SOCIAL_DEMAND_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

