-- ============================================================================
-- 99_RESET.SQL — Reset Social Commerce Analytics & Influencer Intelligence to clean demo state
-- ============================================================================
USE DATABASE SOCIAL_COMMERCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_SOCIAL SUSPEND;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_SENTIMENT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_RECOMMENDATIONS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.INFLUENCER_ROI REFRESH;
ALTER DYNAMIC TABLE CURATED.TRENDING_PRODUCTS REFRESH;
ALTER DYNAMIC TABLE CURATED.CONTENT_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.AUDIENCE_AFFINITY REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM SOCIAL_COMMERCE.RAW.SOCIAL_POSTS → 1200000
-- SELECT COUNT(*) FROM SOCIAL_COMMERCE.RAW.SOCIAL_ORDERS → 680000
-- SELECT COUNT(*) FROM SOCIAL_COMMERCE.CURATED.INFLUENCER_ROI WHERE ROAS > 4.0 → >100

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_UPDATE_RECOMMENDATIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_SENTIMENT RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_SOCIAL RESUME;
